### ISSUE TITLE
eos v0.12.1

### ISSUE THREAD

**Issue by Larumbergera** [patrikhuber/4dface#15]
Hi,

With the eos update v0.12.1, does 4dface work? 

Regards,

Andoni.

**Comment by patrikhuber** [comment]
Hi,

4dface clones eos at a specific tag (0.9.1 I think) so it will always work. I don't currently have time to update 4dface, but in any case, it's just a demo, and anyone can build it with the newest eos version.

**Comment by Larumbergera** [comment]
Ok, Thank you for answering.
