### ISSUE TITLE
Add more PCA coefficients in 4D face to obtain a more accurate morphable model

### ISSUE THREAD

**Issue by codediner** [patrikhuber/4dface#18]
Hi Patrik,

Thank you very much for your release of this genius application. It works prefectly to construct 3D face model in the real time.

But I have a problem when I want to construct a 3D model from different videos of a large variety of faces , il seems that the constrcuted models always look like the moyen face, which means that the deformation of the morphable model is not so obvious, then I check the shape coefficients which has just 5 elements (Perhaps the number of shape coefficients is not abundant), how can I add more PCA coefficients by detail if I want to get a more accurate model which doesn't look like the moyen face that you have offered ??????

Waiting for your answers.

Best regards

**Comment by patrikhuber** [comment]
Hi,

Thanks very much!

You're definitely correct! The more frames we average the shape model over, the more towards the average it goes usually. Therefore, it's smart not to average over all frames (or use a smarter technique - we're currently working on multi-frame fitting).

The `fitting::fit_shape_and_pose` function that's called in 4dface has a parameter to set the number of shape coefficients to fit. Just read the documentation of it.
However, as mentioned above, this will probably not really help in your case.

**Comment by codediner** [comment]
Thank you for your answer, I will take a try with the help of your advice, and I hope you will succed to applying the smarter technique on multi frame fitting for your wonderful project!

Sincerely

**Comment by patrikhuber** [comment]
Thanks! :-)
