### ISSUE TITLE
Gropuing mesh and texture

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/4dface#21]
Hi 

my model contains mesh that grouped into submeshes, so I have texture for each mesh, how can I bind these textures to their corresponding meshes?

**Comment by patrikhuber** [comment]
Hi!

I'm afraid this is kind of outside my knowledge or scope. I suggest you have a look at how this is possible with OpenGL, and through that maybe get some inspiration of how to do it?

I'm going to close this as it's unrelated to 4dface, but feel free to continue the discussion here or report back with any findings.

**Comment by Adra8373** [comment]
Thanks for replying. But I have a question about create_mipmapped_texture function. is it take the whole image or crop part of it ? could please explain the work of it please?

**Comment by patrikhuber** [comment]
It takes the texture (which we call isomap). The only thing it does is create mipmap levels for it and I don't think they're even used in the code, so it's just the texture basically. I recommend you read any Computer Graphics book about texturing if you want to know more. (Also our VISAPP paper contains some details.)
