### ISSUE TITLE
the speed of the method

### ISSUE THREAD

**Issue by zrr1991** [patrikhuber/4dface#22]
Hi, I study face tracking recently, and I find your code. I want to use your code on the phone, so the speed is important for me, but the time of my study is limited, so I want to know the fps of process on Andriod or IOS. Would you mind tell me?
Hope your reply. Thank you very much.

**Comment by patrikhuber** [comment]
Hi,
I can give you some timings for the [eos](github.com/patrikhuber/eos) library. With the 3448 model, it's currently about 30 ms or so per iteration, with the 845 model, around 3 ms. I optimised the model's visibility check locally and got that down to 3 ms and <1 ms respectively - will try to commit that in the next couple of months. These timings are on a i7-7700HQ, using mostly 1 thread.
As always with performance questions: The profiler is your best friend.

**Comment by zrr1991** [comment]
Thanks for your reply!






At 2017-05-25 16:45:32, "Patrik Huber" <notifications@github.com> wrote:


Hi,
I can give you some timings for the eos library. With the 3448 model, it's currently about 30 ms or so per iteration, with the 845 model, around 3 ms. I optimised the model's visibility check locally and got that down to 3 ms and <1 ms respectively - will try to commit that in the next couple of months. These timings are on a i7-7700HQ, using mostly 1 thread.
As always with performance questions: The profiler is your best friend.

**Comment by mathpopo** [comment]
@patrikhuber  hi  ,where can i download 845 model?

**Comment by patrikhuber** [comment]
@mathpopo I've deleted your comment as it is not related to the closed issue here. If you have a question that's not answered yet in the existing open and closed issues, feel free to open a new one.
