### ISSUE TITLE
Moving the face in rendering window

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/4dface#24]
Hi 

I hope you are doing well. 

I have a question about that why the face is moving when the speaker starts to talk, I mean the rendered face is moving not just the lips. Could you answer me, please?

Regards

**Comment by patrikhuber** [comment]
Hi,
I'm not sure what you mean. The head is rotating, yes. But the [translation is set to zero](https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L233-L234).

**Comment by Adra8373** [comment]
Hi 

Thanks for replying. What I meant is that the rendered mesh is moving not just the lips (all the head is moving according to the lips movements. ), I mean it is not as the speaker do when start talking, in usual the head is static, but the lips is moving. 

Regards

**Comment by patrikhuber** [comment]
Ok, I think I maybe see what you mean now. You could use `draw_wireframe(...)` on the original image to verify the fitting results.

I think what you want is maybe better blendshapes, that don't just model expressions, but lip movements.

**Comment by Adra8373** [comment]
Thanks. I used draw_wireframe(...), but I still have the same problem.

**Comment by patrikhuber** [comment]
`draw_wireframe(...)` is only for inspecting, obviously. As mentioned above you may want to use some blendshapes that model lip movements.

**Comment by Adra8373** [comment]
My model contains different lip shapes already, so I do not need to add them separately.

**Comment by patrikhuber** [comment]
Ok, cool! Well, then I guess you need to find out why it happens? ;-)
