### ISSUE TITLE
DrawFace on Video

### ISSUE THREAD

**Issue by msj121** [patrikhuber/4dface#26]
Is there a way to instead of drawing the grid, draw the 3d model in that position?

Thanks.

**Comment by patrikhuber** [comment]
Sure! The app [already does it](https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L235), just to a separate window. You probably need to modify the code a bit to draw into the same buffer. I'd recommend to render with OpenGL anyway if you need speed - you can go through the closed issues a bit to find some more info, other people have asked this before too.
