### ISSUE TITLE
Is it possible to use my own face model?

### ISSUE THREAD

**Issue by YuqinWu** [patrikhuber/4dface#27]
Hi, 
thank you for your amazing project. However, I want to know if I can use my own face model? I noticed that now your project is using a sfm_shape_3448.bin file made by cereal. However, my face model is an obj file. I wish to know how to incorporate my own face model into your project? What jobs are needed to be done? Is your code compatible with different face model?

Thanks!

**Comment by patrikhuber** [comment]
Hi,
Thanks!
You can easily use your own model if it's a PCA model or something similar. Keep in mind we are talking about statistical models of faces (i.e. PCA models), and not just a single mesh (i.e. .obj file). With a single .obj mesh, you obviously can't create a face model (model of face variation).

**Comment by CodingGou** [comment]
@patrikhuber  how to transform my own head model to a PCA model ?

**Comment by patrikhuber** [comment]
@CodingGou Please read my above comment. I suggest you read up some literature about Morphable Models and statistical/PCA shape models.
