### ISSUE TITLE
uv-mapping of a custom head model

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/4dface#29]
Hi 

I am using full head model. So I do not need to use the extracted texture from the video frame. When I passed the texture image to create_mipmapped_texture function I got a distorted texture, could explain to me how can I solve this problem? Do I use the correct function? 

The result that I got is showed in the figure. 

Regards 
![fig](https://user-images.githubusercontent.com/20519118/28883985-287e8c6e-77a8-11e7-99e7-b5cc5178072d.jpg)

**Comment by patrikhuber** [comment]
I'm really not sure what you're doing and trying to do, sorry!

**Comment by Adra8373** [comment]
I am trying to map the attached picture to the head model, using  create_mipmapped_texture function. 
![male111](https://user-images.githubusercontent.com/20519118/28915079-e22ba59c-7835-11e7-9cf4-65fd4143ee76.jpg)

**Comment by patrikhuber** [comment]
It looks like your uv coordinates might be wrong. You should verify that it works in MeshLab or Blender first.

Also the texturing support in eos is quite basic so there might be some issues if your uv coordinates contain the same vertex mapped to multiple triangles on the uv-map.

**Comment by Adra8373** [comment]
Thanks for replying. I tested that in 3DMax and It works good. But the uv coordinates are 6188 and the vertices are 5850, they are not equal. That is could be the problem, am I right?

**Comment by patrikhuber** [comment]
Ok, good.

> the uv coordinates are 6188 and the vertices are 5850 [...] That is could be the problem, am I right?

Yes, exactly. eos currently only supports simple texturing where both numbers are the same. 
You can try to generate a texture map without seams (i.e. just a flattening of the mesh), if that's possible with your mesh topology.
Otherwise you don't need the rendering (texturing) in eos for anything, you can render using OpenGL (or export an obj and use 3ds Max).

**Comment by Adra8373** [comment]
Many thanks for replying and for help.

**Comment by CodingGou** [comment]
i am try to use a picture to reconstruction 3d face on my own custom head model, what should i do?Could  you tell me how to use the eos library? Sincerely waiting for your answer！

**Comment by patrikhuber** [comment]
@CodingGou Sorry, I am deleting your comment here, as it is completely unrelated to this issue. The documentation and GitHub readme are there to tell you how you can start using the eos library.
