### ISSUE TITLE
Don't have "../4Dface/data/face_landmarks_model_rcr_68.bin"

### ISSUE THREAD

**Issue by Coding4mejie** [patrikhuber/4dface#3]
There's no face_landmarks_model_rcr_68.bin in the 4dface document,I try face_landmarks_model_rcr_22.bin,it runs sucessfully,but the landmarks only have 22,Where can I get the face_landmarks_model_rcr_68.bin?Thank you very much.

**Comment by patrikhuber** [comment]
Just run cmake, it will [download](https://github.com/patrikhuber/4dface/blob/master/CMakeLists.txt#L91) it.

**Comment by chrisluu** [comment]
I can't download the face model "face_landmarks_model_rcr_68.bin". Can you send it to me via email(dearchrisluu@gmail.com) or any other ways is ok cause I can't visit your personal web site. Thanks for your help.

**Comment by patrikhuber** [comment]
@chrisluu I've emailed it (hope it worked, it's 85 MB).

**Comment by chrisluu** [comment]
@patrikhuber Hi, I succeed in downloading it.Thanks for your help. I can visit your web site via vpn, but it is not stable sometimes.

**Comment by nikoong** [comment]
@patrikhuber Hi，I can't access patrikhuber.ch either. Can you send  "face_landmarks_model_rcr_68.bin" to my email(nikoong@smail.nju.edu.cn)?

**Comment by patrikhuber** [comment]
@nikoong You can download the model here: https://drive.google.com/file/d/0B2FFdHlMfJl_UG51UlIzTk9NWms/view?usp=sharing

**Comment by qriuui** [comment]
@patrikhuber  Thank you! I have built 4dfave successfully.

**Comment by nikoong** [comment]
@patrikhuber  Thank you for the  link! I have built 4dface successfully.

**Comment by mathpopo** [comment]
@patrikhuber hi, i use vpn,but
-- Downloading face_landmarks_model_rcr_68.bin (84.6 MB)...
-- [download 100% complete]
CMake Error at CMakeLists.txt:98 (message):
  Error downloading the file: 1; "Unsupported protocol".  Please delete the
  file if it has been created and re-run cmake or download the file manually
  and put it into the root of the build directory.

**Comment by patrikhuber** [comment]
@mathpopo You can check around line 98 in the CMake file that the error mentions, you'll find the download URL there and can manually download it. Alternatively, two messages above in this thread, I've posted a Google Drive link with the download.
