### ISSUE TITLE
Shortcuts in the 4dface app

### ISSUE THREAD

**Issue by quentbau** [patrikhuber/4dface#31]
Good morning,
First I would like to thank you for making such a cool software available as open source! I am running it on ubuntu throught the console command "cd install/bin" and "./4dface -i test.mp4", test.mp4 being a video file present in install/bin. I cannot run the application by double clicking on it in the folder install/bin directly, do you know if it is normal? 
It opens two windows: my video with a green mesh on top of the face and a small render window where the 3d imaging of the face appears. My issue is I am stuck here with the functionalities: i cannot use the shortcuts q, r ans especially s in order to save the 3d model (mesh+texture). Could you please explain how to export the 3d model? Is there a command i could write in the console?

Thanks a lot for your work,
Quentin

**Comment by patrikhuber** [comment]
Hi!

I think when you double-click the file, it starts it with the default parameters, which expect the model and all the stuff to be in a certain directory relative to where you run the executable from. If these paths all match, I'm not sure why it wouldn't work, I usually use the terminal to run such kind of apps :-)

The shortcuts should really work. Have you tried focusing the various windows? Maybe the focus is in the wrong window? Or maybe OpenCV changed something in one of their latest versions, though I think that's unlikely to be the cause of error here.
You can always modify the code to save whatever you want to save :-)

**Comment by quentbau** [comment]
Thank you very much for answering my question! I though I was not focusing the good window as well but it was not the case. I finally changed the code so that it exports the 3Dmodel and texture before ending. 
Thanks a lot!
