### ISSUE TITLE
toml module is missing

### ISSUE THREAD

**Issue by qyalexwen** [patrikhuber/4dface#33]
I created symbolic links for the external modules eos and 
When I build, it still has errors: 

~/dev/4dface/build$ make 
[ 50%] Building CXX object CMakeFiles/4dface.dir/apps/4dface.cpp.o
In file included from /home/alex/dev/4dface/4dface-master/apps/helpers.hpp:26:0,
                 from /home/alex/dev/4dface/4dface-master/apps/4dface.cpp:20:
/home/alex/dev/4dface/4dface-master/external/eos/include/eos/core/LandmarkMapper.hpp:25:20: fatal error: toml.hpp: No such file or directory
compilation terminated.

**Comment by patrikhuber** [comment]
I think you may need to update eos or update its submodules, i.e., in your eos directory:
```
$ git checkout master
$ git pull
$ git submodule update --init --recursive
```

Possibly you also need to add the toml11 directory to 4dface's include paths. Note that 4dface uses quite an old eos version (0.9.1) - I've never had the time to update that submodule and adjust the 4dface code accordingly. But it would be trivial.
If you want to do any serious work or evaluation of eos, I strongly suggest you use the latest eos version though from github.com/patrikhuber/eos.

**Comment by qyalexwen** [comment]
After updated all the external libraries, issue resolved.
