### ISSUE TITLE
every video outputs the same 3d face shape

### ISSUE THREAD

**Issue by mrbemani** [patrikhuber/4dface#34]
I have tried 4dface on several videos. All of them when I press 's', outputs the extactly same 3d face model, with different textures. Is that normal? Or I did something wrong?

```
./4dface -i test.mov
```

----
ok, I see the problem. nose shapes are not quite right on eastern faces. like small nose faces.

**Comment by patrikhuber** [comment]
Hi,

How do you arrive at the conclusion that they are all the same 3D face shape? My guess is that they are subtly different. Keep in mind you are using shape-to-landmarks fitting, so the shape will be fitted to the landmarks, which captures coarse structure like face width, height and shape very well, but doesn't capture the finer details.
How well the nose shape can be captured therefore also mainly depends on how many landmarks you use around the nose.

I am closing this as it doesn't look like an issue with this 4dface demo or eos, but please feel free to re-open or write back if you discover any issues.
Thanks!
