### ISSUE TITLE
how to read the NoseTri.bin.bin .EyeballsTri.bin...

### ISSUE THREAD

**Issue by zhoushiwei** [patrikhuber/4dface#35]
Hi, how to get the data in regions file ,can you give me the code ? @patrikhuber

**Comment by patrikhuber** [comment]
Hi!
These files are not part of eos, so I suggest you enquire with CVSSP, where you obtained these files. See the enquiry email address given on http://cvssp.org/facemodel.

I think it's simple though, it should just be a binary list of integers (32-bit probably) which you can read one after each other.

I am closing this but feel free to post back the exact details when you have them, it may help others.
