### ISSUE TITLE
How to implement merged isomap and visualize mesh in Python

### ISSUE THREAD

**Issue by jjjjohnson** [patrikhuber/4dface#38]
Hi @patrikhuber,
I checked the `help(eos)` and cannot find any info about merging isomap. And it is in the `helpers.hpp` for cpp version. Is is something I should write as the helper function?

Thanks a lot!
Junjie

**Comment by patrikhuber** [comment]
Hi Junjie,

I think if you want to merge isomaps in Python, you best write the code for that by yourself, depending on how you want to merge. eos will return the images as NumPy arrays and you could process them with OpenCV's Python bindings or something like that.
As for visualising the mesh, you'd probably best use OpenGL or something like that to draw the vertices and eos/4dface return in the `eos::core::Mesh`.
You could also implement the `draw_wireframe` function in Python, if that's what you wanted, it's a straight copy&paste.
