### ISSUE TITLE
Could not find Eigen3 with Visual studio 2017

### ISSUE THREAD

**Issue by muzammaljanjua** [patrikhuber/4dface#41]
I have done all but still getting this error

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "2.91.0")		C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake	137	

on this place

macro(_FPHSA_FAILURE_MESSAGE _msg)
  if (${_NAME}_FIND_REQUIRED)
    message(FATAL_ERROR "${_msg}")
  else ()
    if (NOT ${_NAME}_FIND_QUIETLY)
      message(STATUS "${_msg}")
    endif ()
  endif ()
endmacro()

Please help to solve, thank you

**Comment by patrikhuber** [comment]
This seems like an issue on your system with how you use or call cmake to set up the project. I recommend you follow the instructions, and post to [Stackoverflow](http://stackoverflow.com) with these sorts of questions, since it is not a developer issue.
Thanks!
