### ISSUE TITLE
How to change the shape&expression model in 4dface?

### ISSUE THREAD

**Issue by nomorecoding** [patrikhuber/4dface#43]
I've tried to replace shape model, expression model and contour correspondence with the surrey 29587 version, but it aborted always, I wonder how could I use a higher resolution model to fit photos?

**Comment by patrikhuber** [comment]
Hi,
Switching to the high-res model should work. If it doesn't, please provide more information, like for example the actual error. If there isn't any error message, run a Debug build and check the line where it fails. Should be an easy fix.

**Comment by nomorecoding** [comment]
Thanks for your fast reply! It "works", I mean the program could run, but I get almost the same face model using different pictures. I'm not sure what should I do. I chose 10 iterations and 300.0 shape regularization by the way.

**Comment by patrikhuber** [comment]
It seems to me like it is working and there isn't any issue. Please feel free to re-open the issue with a better description / problem report if there is any issue. Thanks.
