### ISSUE TITLE
How can I get the HD expression_blendshapes_XXX.bin

### ISSUE THREAD

**Issue by chenlinweiSCU** [patrikhuber/4dface#5]
Dear Patrik,

Thanks for your code, which is very helpful for my research. I want to try the HD morphable model.  I have downloaded the HD "sfm_shape_16759.bin" and "sfm_shape_29587.bin", but I don't find where to download the corresponding "expresssion_blendshapes_167559.bin" and "expresssion_blendshapes_29587.bin" files, as well as "ibug2did.txt" files? I wonder whether you provide these files for test?

Best Regards
Linwei

**Comment by patrikhuber** [comment]
Dear Linwei,

The file `ibug2did.txt` stays the same, you don't need a different one there.

With regards to the blendshapes, I need to check our download folder but I think you are right and the blendshapes might be missing. I'm off to a conference and don't have time to have a look at it right now, can you drop me an email, and I'll just send them to you for now?

Best regards,
Patrik

**Comment by patrikhuber** [comment]
Sorry this took so long to resolve.

All expression blendshapes are now available for download via the CVSSP download link you received in your email. Let me know if there's any more issues. Thanks!

**Comment by zhoushiwei** [comment]
Hi, can you give me the download link?

**Comment by patrikhuber** [comment]
@zhoushiwei You can find the link to register and get the download link here: http://cvssp.org/facemodel
