### ISSUE TITLE
Does 4dface fit only to landmarks or edges as well

### ISSUE THREAD

**Issue by shubhamag** [patrikhuber/4dface#50]
Hi,

Thank you for making 4dface available.
I notice that 4dface depends on eos under the hood, and eos has been modified so that it fits to both landmarks and edges, based on "Fitting a 3D Morphable Model to Edges: A Comparison Between Hard and Soft Correspondences" . 
So my question was, is 4dface currently fitting to both, or just landmarks (as in simple fit of eos) ?

Thank you, and apologies in advance if this isn't the right place to post this.

**Comment by patrikhuber** [comment]
Hi,

This 4dface research demo fits to landmarks (inner face & dynamic contour landmarks). You can easily see [just by glancing over the demo code](https://github.com/patrikhuber/4dface/blob/70d4d5f77c3240be9412521b1d92d5701381e8ab/apps/4dface.cpp#L213).

I want to highlight again the note at the top of the README:

> ### Note: This is a research demo from 2015/2016. 4dface has since been commercialised and an improved, up-to-date version is available on [www.4dface.io](https://www.4dface.io). This repository also contains an older version of the morphable face model fitting library _eos_. _eos_ is still in active development, head over to [github.com/patrikhuber/eos](https://github.com/patrikhuber/eos) for the latest version.

So I would strongly suggest you use the latest version of eos directly. You can still use the 4dface demo code as a skeletton, or perhaps even update the eos submodule in this repo to the latest version and it may compile and run right away, but I am currently not actively maintaining this demo anymore. Eos, on the other hand, is actively in development and maintained.
