### ISSUE TITLE
No warning, No error, No make...

### ISSUE THREAD

**Issue by JunfengZZZZhou** [patrikhuber/4dface#51]
Hi, I have been stuck here for many days...
I follow the instruction but after I do the cmake ....., no make file showed. so I cannot do the make. I'm new to related things so I have hard time figuring out what's wrong. Please help me, thank you.
the following are the command line and [result.]
`C:\ZhouJunfeng\project\4dface\build>cmake -C ../4dface/initial_cache.cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DOpenCV_haarcascades_DIR=C:\\ZhouJunfeng\\project\\vcpkg\\vcpkg\\packages\\opencv_x64-windows\\share\\opencv\\haarcascades\\ ../4dface/ -G "Visual Studio 15 2017"
loading initial cache file ../4dface/initial_cache.cmake
-- The C compiler identification is MSVC 19.16.27027.1
-- The CXX compiler identification is MSVC 19.16.27027.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: C:/ZhouJunfeng/project/vcpkg/vcpkg/installed/x64-windows (found suitable version "3.4.3", minimum required is "3") found components:  core imgcodecs imgproc highgui videoio objdetect
-- OpenCV include dir found at C:/ZhouJunfeng/project/vcpkg/vcpkg/installed/x64-windows/include;C:/ZhouJunfeng/project/vcpkg/vcpkg/installed/x64-windows/include/opencv
-- OpenCV library dir found at C:\ZhouJunfeng\project\vcpkg\vcpkg\packages\opencv_x64-windows\lib
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
-- Boost found at C:/tools/boost_1_59_0
-- Eigen3 found: TRUE
-- Eigen3 include dir found at C:\ZhouJunfeng\project\vcpkg\vcpkg\installed\x64-windows\include\eigen3
-- Eigen3 version: 3.3.7
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ZhouJunfeng/project/4dface/build`
<img width="1019" alt="微信图片_20190401112829" src="https://user-images.githubusercontent.com/48046716/55301860-4a886080-5471-11e9-9023-6de5856b2a69.png">

**Comment by patrikhuber** [comment]
I see that you were probably able to figure out that you have to open the created solution and build with Visual Studio. You can also use `cmake --build . --config <Config> --target <Target>` where <Config> can be Release, Debug etc., and <Target> an optional target to build (e.g. the library, examples, or install target).

For the future, I would suggest to post such questions on StackOverflow or a similar help website, since this is not an issue about this software.

**Comment by JunfengZZZZhou** [comment]
> I see that you were probably able to figure out that you have to open the created solution and build with Visual Studio. You can also use `cmake --build . --config <Config> --target <Target>` where can be Release, Debug etc., and an optional target to build (e.g. the library, examples, or install target).
> 
> For the future, I would suggest to post such questions on StackOverflow or a similar help website, since this is not an issue about this software.

Yes, I finally get it done in Visual Studio. But I still cannot understand why that happened. Thank you very much for the reply and I think post the questions on help website will definitely help beginners like me in similar circumstance.
