### ISSUE TITLE
Make Install Error

### ISSUE THREAD

**Issue by nathan727** [patrikhuber/4dface#52]
Hi,

I'm having some errors with the make install step, I've followed the readme steps. This is the error I'm getting.

nathan@nathan-HP-ENVY-x360-Convertible:~/build2$ make install
[100%] Built target 4dface
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/4dface
CMake Error at cmake_install.cmake:47 (file):
  file INSTALL cannot copy file "/home/nathan/build2/4dface" to
  "/usr/local/bin/4dface".

Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1

Any help would be appreciated and great work with all your projects.

**Comment by patrikhuber** [comment]
You're trying to copy files to `/usr/local/bin/`, probably you don't have sudo rights. I'd recommend installing to a local user directory.

**Comment by nathan727** [comment]
cheers, is there any where I can read up on how to do that?
thanks.

**Comment by patrikhuber** [comment]
Google, CMake documentation/book, StackOverflow.
