### ISSUE TITLE
error when run 4dface

### ISSUE THREAD

**Issue by WwYyFan** [patrikhuber/4dface#53]
```
Error reading the RCR model "../share/face_landmarks_model_rcr_68.bin": Failed to read 14797344 bytes from input stream! Read 3905020
```

**Comment by WwYyFan** [comment]
@patrikhuber 
Please tell me how to solve this problem.

**Comment by patrikhuber** [comment]
Hi @WwYyFan,
The first step would be a proper description of what exactly you've done and an analysis of what you've tried so far and what/why it still doesn't work.

**Comment by WwYyFan** [comment]
@patrikhuber   
My system is ubuntu 16.04 and I did the steps as you say in readme.md  , but when I run the 4dface app ,it occur ```Error reading the RCR model "../share/face_landmarks_model_rcr_68.bin": Failed to read 14797344 bytes from input stream! Read 3905020```

**Comment by patrikhuber** [comment]
Well, did the file `face_landmarks_model_rcr_68.bin` download successfully? Perhaps try re-downloading it manually? (You can find the URL in the CMakeLists.txt). Try manually specifying the path? Etc.
