### ISSUE TITLE
How to save the obj files

### ISSUE THREAD

**Issue by Monjur-Mahathir** [patrikhuber/4dface#54]
Is there any way to continuously save the 3d face models so that I can get a 4d obj file?i can see the rendering but cant save them

**Comment by patrikhuber** [comment]
Hi, sorry for the late reply. You can use eos's `write_obj(...)` or `write_textured_obj(...)` function - it's already used in the current example (https://github.com/patrikhuber/4dface/blob/70d4d5f77c3240be9412521b1d92d5701381e8ab/apps/4dface.cpp#L253), you could just call that every frame.
