### ISSUE TITLE
Error in running the INSTALL target

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/4dface#7]
Hi  Patrik

Thanks for the code 

I have this error message when I try to build the install project in /visual Studio 2015. 

 Unhandled exception at 0x000007FEFCCEA06D in 4dface.exe: Microsoft C++ exception: cereal::Exception at memory location 0x00000000001C0F40.

**Comment by patrikhuber** [comment]
Hi,

I don't think this error can occur when _building_, so I don't think this has anything to do with the `INSTALL` target. I think you're _running_ 4dface.exe actually.
In that case can you please run it in debug mode and pinpoint the exact line where the problem occurs in the 4dface code? You'll find all you need in the callstack window.
It might just be that you give it a wrong path or file.

**Comment by Adra8373** [comment]
Hi 

Thanks It works now 

But I want to run on a video, how can I do that. It just works with a camera. 

Regards

**Comment by patrikhuber** [comment]
I don't know what you mean with "It just works with a camera", but how you run it on videos depends on your database and landmarks. In any case, you can have a look at [4dface](https://github.com/patrikhuber/4dface).

**Comment by Adra8373** [comment]
This is an error that I got 

C:\phd\codes\4dface-master\build\Debug>4dface.exe -i Copy of bgia5a.mpg
warning: Error opening file (../../modules/highgui/src/cap_ffmpeg_impl.hpp:537)
Couldn't open the given file or camera 0.

**Comment by patrikhuber** [comment]
Try without spaces in the filename. If that doesn't work either, maybe your OpenCV has problems reading mpg files?
